name: Generate Changelog

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Auto-generate CHANGELOG
        uses: BobAnkh/auto-generate-changelog@v1.3.2
        with:
          REPO_NAME: uChusta/StratusBot
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PATH: CHANGELOG.md
          BRANCH: main
          COMMIT_MESSAGE: 'docs(changelog): update release notes'
          TYPE: 'feat:Feature,fix:Fix,break:Breaking Change'
